### DISCUSSION TITLE
EA-LSTM in config.yml

### DISCUSSION THREAD

**Discussion by mengziwen2000** [neuralhydrology/neuralhydrology#130] [Q&A] [answered]
After I read [MC-LSTM: Mass-Conserving LSTM](https://doi.org/10.48550/arXiv.2101.05186) and [Towards learning universal, regional, and local hydrological behaviors via machine learning applied to large-sample datasets](https://doi.org/10.5194/hess-23-5089-2019), I always had problems training the model during the configuration of EA-LSTM's cfg.yml, and the NSE kept dropping from the first generation of validation (which only reached 0.5) and was less than zero. Here is most of my cfg.yml.
```
validate_every: 3
validate_n_random_basins: 447
metrics:
  - NSE
model: ealstm
head: regression
output_activation: linear
hidden_size: 128
initial_forget_bias: 3
statics_embedding: 
  type: fc
  hiddens: 
    - 128
    - 64
    - 1
  activation: linear
  dropout: 0.3
optimizer: Adam
loss: NSE
allow_subsequent_nan_losses: 1000

clip_gradient_norm: 1
predict_last_n: 1
num_workers: 8
log_interval: 5
log_tensorboard: True
save_weights_every: 1
log_n_figures: 1

static_attributes:
  - elev_mean
  （27）

forcings:
  - maurer
  - daymet
  - nldas

dynamic_inputs:
  - PRCP(mm/day)_nldas
  - PRCP(mm/day)_maurer
  - prcp(mm/day)_daymet
  - srad(W/m2)_daymet
  - tmax(C)_daymet
  - tmin(C)_daymet
  - vp(Pa)_daymet

target_variables:
  - QObs(mm/d)

clip_targets_to_zero:
  - QObs(mm/d)
```
