### DISCUSSION TITLE
Predict hourly time steps using both daily and hourly data

### DISCUSSION THREAD

**Discussion by jdevillersvortex** [neuralhydrology/neuralhydrology#208] [Q&A] [answered]
Hello,
I'm looking to predict discharge from hourly rainfall data. I'd like to use rainfall data from the last year (for example) but this would require too much training time on the machine I'm using. Looking at some of your work, I got the impression that the MTS-LSTM model could meet my requirements: I'd use rainfall data at a daily time step for the start of the sequence on a first model, then hourly data only for the end of the sequence (e.g. the last 2 weeks). After a few tests, this greatly reduces training time and my loss (the NSE*) converges well. However, the validation metrics are not good as soon as I use more than 1 basin and I'm having trouble understanding why. The thing is I'm not at all interested in a daily prediction, but the model as I've configured it inevitably gives a daily prediction which is used both in the loss and, above all, the validation metrics. I've tried setting predict_last_n to 0 for the 1D frequency but I get this error: 

```
"Traceback (most recent call last):
  File "/home/ubuntu/neuralhydrology/neuralhydrology/nh_run.py", line 173, in <module>
    _main()
  File "/home/ubuntu/neuralhydrology/neuralhydrology/nh_run.py", line 43, in _main
    start_run(config_file=Path(args["config_file"]), gpu=args["gpu"])
  File "/home/ubuntu/neuralhydrology/neuralhydrology/nh_run.py", line 76, in start_run
    start_training(config)
  File "/home/ubuntu/neuralhydrology/neuralhydrology/training/train.py", line 20, in start_training
    trainer.train_and_validate()
  File "/home/ubuntu/neuralhydrology/neuralhydrology/training/basetrainer.py", line 227, in train_and_validate
    self.validator.evaluate(epoch=epoch,
  File "/home/ubuntu/neuralhydrology/neuralhydrology/evaluation/tester.py", line 267, in evaluate
    dates[lowest_freq][:, -1],
    ~~~~~^^^^^^^^^^^^^
KeyError: '1D'"
```

My aim is really to get an hourly prediction that uses daily data for the first time steps of the input sequence and hourly data for the very last time steps. Do you know if there's already a way of configuring mts-lstm so that the validation metrics are based on hourly predictions only and not daily ones? Or is there a better way to do so ? 
Thank you in advance for your help.

Here's an extract from my configuration file:
```
# --- Validation configuration ---------------------------------------------------------------------
validate_every: 1
validate_n_random_basins: 5
cache_validation_data: true
metrics:
- NSE
- KGE
- Alpha-NSE
- Beta-NSE

# --- Model configuration --------------------------------------------------------------------------
model: mtslstm
head: regression
output_activation: linear

hidden_size:
  1D: 64
  1h: 64
initial_forget_bias: 3
output_dropout: 0.4

shared_mtslstm: false

embedding_hiddens:
- 30
- 20
- 64

# --- Training configuration -----------------------------------------------------------------------
optimizer: Adam
loss: NSE
regularization:
learning_rate:
  0: 0.0005
  20: 0.0001
  50: 5e-05
batch_size: 256
epochs: 100
clip_gradient_norm: 1

use_frequencies:
- 1D
- 1h

#no_loss_frequencies:
#- 1D

predict_last_n:
  1D: 0
  1h: 24
seq_length:
  1D: 365
  1h: 336

num_workers: 3
log_interval: 5
log_tensorboard: true
log_n_figures: 0
save_weights_every: 50
save_validation_results: false

allow_subsequent_nan_losses: 10
```
