### ISSUE TITLE
Finetuning on basins

### ISSUE THREAD

**Issue by tommylees112** [neuralhydrology/neuralhydrology#18]
Hi guys!  (repeating an email on here - realised that the formatting and links are really helpful, ignore the email!)

I wanted to finetune some models on specific basins. 

# What arguments do i need in the configs to finetune?

# 1) `base_run_dir`
I found this information in the docs:
```
neuralhydrology.nh_run.finetune(config_file: pathlib.Path = None, gpu: int = None)
Finetune a pre-trained model.

Parameters
config_file (Path, optional) – Path to an additional config file. Each config argument in this file will overwrite the original run config. The config file for finetuning must contain the argument base_run_dir, pointing to the folder of the pre-trained model.

gpu (int, optional) – GPU id to use. Will override config argument ‘device’.
```
So I need to specify a new argument: `base_run_dir`

# 2) `finetune_modules`
[basetrainer.py L106-113](https://github.com/neuralhydrology/neuralhydrology/blob/master/neuralhydrology/training/basetrainer.py#L106-L113)
```python
        if isinstance(self.cfg.finetune_modules, list):
            for module_part in self.cfg.finetune_modules:
                if module_part in self.model.module_parts:
                    module = getattr(self.model, module_part)
                    for param in module.parameters():
                        param.requires_grad = True
                else:
                    unresolved_modules.append(module_part)

```
I guess therefore I need to assign values to the argument `finetune_modules` in the yaml file. What parameters can this argument take? Is it "head" or "lstm" ?

```yml
finetune_modules: 
```

# 3) `train_basin_file`
```yaml
train_basin_file: /home/tommy/neuralhydrology/data/finetune_basin_list.txt
validation_basin_file: /home/tommy/neuralhydrology/data/finetune_basin_list.txt
test_basin_file: /home/tommy/neuralhydrology/data/finetune_basin_list.txt
```

Are there any other arguments that I have overlooked or got wrong?

Thanks guys! 
Tommy
