### ISSUE TITLE
config.log is often empty, is this a bug or my own mistake?

### ISSUE THREAD

**Issue by Flash-Of-Thunder** [neuralhydrology/neuralhydrology#80]
Hello, @kratzert and team,

Hope all is going well (as well as it can be) and the child(ren?) is growing in good health. My sincere well wishes for you and your neighbors in this unsettling time.

Basic question, I want to look at my log at .../runs/.../output.log file but most of the time it is blank. Any idea why this might be happening and how to fix it?

My config file:

```
# --- Experiment configurations --------------------------------------------------------------------

# experiment name, used as folder name
experiment_name: 530_trimmed

# files to specify training, validation and test basins (relative to code root or absolute path)
train_basin_file: 530_trimmed_train.txt
validation_basin_file: 530_trimmed_validation.txt
test_basin_file: 530_land_use_changing_test.txt

# training, validation and test time periods (format = 'dd/mm/yyyy')
train_start_date: "01/01/2005"
train_end_date: "31/12/2014"
validation_start_date: "01/01/2000"
validation_end_date: "31/12/2004"
test_start_date: "01/01/2000"
test_end_date: "30/12/2020"

# which GPU (id) to use [in format of cuda:0, cuda:1 etc, or cpu or None]
device: cuda:0

# --- Validation configuration ---------------------------------------------------------------------

# specify after how many epochs to perform validation
validate_every: 2

# specify how many random basins to use for validation
validate_n_random_basins: 518

# specify which metrics to calculate during validation (see neuralhydrology.evaluation.metrics)
# this can either be a list or a dictionary. If a dictionary is used, the inner keys must match the name of the
# target_variable specified below. Using dicts allows for different metrics per target variable.
metrics:
  - NSE

# --- Model configuration --------------------------------------------------------------------------

# base model type [lstm, ealstm, cudalstm, embcudalstm, mtslstm]
# (has to match the if statement in modelzoo/__init__.py)
model: cudalstm

# prediction head [regression]. Define the head specific parameters below
head: regression

# ----> Regression settings <----
output_activation: linear

# ----> General settings <----

# Number of cell states of the LSTM
hidden_size: 150

# Initial bias value of the forget gate
initial_forget_bias: 3

# Dropout applied to the output of the LSTM
output_dropout: 0.2

# --- Training configuration -----------------------------------------------------------------------

# specify optimizer [Adam]
optimizer: Adam

# specify loss [MSE, NSE, RMSE]
loss: NSE

# specify learning rates to use starting at specific epochs (0 is the initial learning rate)
learning_rate:
  0: 1e-2
  2: 5e-3
  4: 1e-3
  6: 1e-4  
  8: 1e-5

# Mini-batch size
batch_size: 256

# Number of training epochs
epochs: 12

# If a value, clips the gradients during training to that norm.
clip_gradient_norm: 1

# Defines which time steps are used to calculate the loss. Can't be larger than seq_length.
# If use_frequencies is used, this needs to be a dict mapping each frequency to a predict_last_n-value, else an int.
predict_last_n: 1

# Length of the input sequence
# If use_frequencies is used, this needs to be a dict mapping each frequency to a seq_length, else an int.
seq_length: 365

# Number of parallel workers used in the data pipeline
num_workers: 10

# Log the training loss every n steps
log_interval: 1

# If true, writes logging results into tensorboard file
log_tensorboard: True

# If a value and greater than 0, logs n random basins as figures during validation
log_n_figures: 1

# Save model weights every n epochs
save_weights_every: 1

# --- Data configurations --------------------------------------------------------------------------

# which data set to use [camels_us, camels_gb, global, hourly_camels_us]
dataset: generic

# Path to data set root
data_dir: /home/flashy_thunder_kid/Projects/data_dir



dynamic_inputs:
  - prcp
  - tmax
  - tmin
  - dayl
  - Water
  - Developed
  - Barren
  - Forest
  - Planted
  - Wetlands
  - Shrubland
  - Herbaceous

static_attributes:
  - DRAIN_SQKM
  - BAS_COMPACTNESS
  - T_MAX_BASIN
  - PPTAVG_BASIN
  - PPTAVG_SITE
  - ELEV_MEAN_M_BASIN
  - SLOPE_PCT
  - LAT_CENT
  - LONG_CENT
  - WD_BASIN
  - WD_SITE
  - SNOW_PCT_PRECIP
  - ELEV_MAX_M_BASIN
  - ELEV_MIN_M_BASIN
  - ASPECT_DEGREES
  - HGA
  - HGB
  - HGC
  - HGD
  - ROCKDEPAVE


# which columns to use as target
target_variables:
  - QObs

# clip negative predictions to zero for all variables listed below. Should be a list, even for single variables.
clip_targets_to_zero:
  - QObs

```

Apologies in advance if this is some gross oversight on my side, but I had checked the documentation and didn't see my solution.

Warm regards,

Samson
